---
- hosts: ansiblevm2
  become: yes
  tasks:
  - name: Check if dotnet-sdk is installed
    shell: dpkg-query -W -f='${Status}' dotnet-sdk-2.1
    register: is_installed
    failed_when: no
    changed_when: no

  - name: Download Microsoft deb
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
      dest: /tmp/packages-microsoft-prod.deb
    when: is_installed.rc != 0
      
  - name: Install Microsoft deb
    command: sudo dpkg -i /tmp/packages-microsoft-prod.deb
    when: is_installed.rc != 0

  - name: apt-transport-https is up-to-date.
    apt:
      name: apt-transport-https
      state: present

  - name: Runs apt-get update, if last run more than one hour ago.
    apt: 
      update_cache: yes
      cache_valid_time: 3600

  - name: dotnet-sdk-2.1 is present.
    apt:
      name: dotnet-sdk-2.1
      state: present